namespace NbgDev.SwitchMan.Switches.OmadaController.OmadaApi;

internal record OperationResponseLanNetworkOpenApiGridVoLanNetworkQueryOpenApiVo(int ErrorCode, string Msg, LanNetworkOpenApiGridVoLanNetworkQueryOpenApiVo Result);
