<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>767d9ad5-12d7-4907-bec9-ffee906ce7ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NbgDev.SwitchMan.Switches.OmadaController\NbgDev.SwitchMan.Switches.OmadaController.csproj" />
    <ProjectReference Include="..\NbgDev.SwitchMan.Switches.TLSG2008\NbgDev.SwitchMan.Switches.TLSG2008.csproj" />
  </ItemGroup>

</Project>
